# Generated by Django 5.0 on 2024-04-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRN', '0003_grn_grn_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='import_PR',
            fields=[
                ('measurement', models.TextField(blank=True, null=True)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('shipment_type', models.TextField(blank=True, null=True)),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('PR_no', models.TextField(primary_key=True, serialize=False)),
                ('order_no', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('site_name', models.TextField()),
                ('approved_by', models.TextField(blank=True, null=True)),
                ('PR_total_price', models.FloatField(blank=True, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='Pending', null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('loading_port', models.TextField(blank=True, null=True)),
                ('discharge_port', models.TextField(blank=True, null=True)),
                ('destination', models.TextField(blank=True, null=True)),
                ('freight', models.FloatField(blank=True, null=True)),
                ('djbouti_costs', models.FloatField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='import_PR_item',
            fields=[
                ('id_numeric', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('measurement_type', models.TextField(blank=True, null=True)),
                ('hs_code', models.TextField(blank=True, null=True)),
                ('PR_no', models.ForeignKey(blank=True, db_column='PR_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='GRN.import_pr')),
            ],
        ),
    ]
