# Generated by Django 5.0 on 2024-03-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='remaining',
        ),
    ]
