# Generated by Django 5.0 on 2024-04-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MR", "0002_remove_inventory_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="mr_item",
            name="measurement_type",
            field=models.TextField(blank=True, null=True),
        ),
    ]
