# Generated by Django 5.0 on 2024-04-12 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MR", "0003_mr_item_measurement_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mr_item",
            old_name="measurement_type",
            new_name="unit",
        ),
    ]
