# Generated by Django 5.0 on 2024-04-12 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FGRN", "0002_fgrn_recieved_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fgrn",
            old_name="recieved_BY",
            new_name="recieved_by",
        ),
    ]
